In [27]:
import numpy as np

A = np.array([[-21, 6, 3, 12, 9],
              [7, -2, -1, -4, -3],
              [0, 0, 0, 0, 0],
              [35, -10, -5, -20, -15],
              [-14, 4, 2, 8, 6]])

# compute rank of A
rank = np.linalg.matrix_rank(A)
print(f"rank: {rank}")

# Compute the SVD of A
U, S, V = np.linalg.svd(A)
s_value = S[0]

v = V[0] * np.sqrt(s_value)
u = U[:, 0] * np.sqrt(s_value)
print(f"v: {v}")
print(f"u: {u}")

rank: 1
v: [ 5.86755837 -1.67644525 -0.83822262 -3.3528905  -2.51466787]
u: [-3.57900146  1.19300049  0.          5.96500244 -2.38600097]


In [25]:
#let's check the result of multiplication
test_A = np.outer(u, v)
print(f"test_A: \n{test_A}")


test_A: 
[[-21.   6.   3.  12.   9.]
 [  7.  -2.  -1.  -4.  -3.]
 [  0.  -0.  -0.  -0.  -0.]
 [ 35. -10.  -5. -20. -15.]
 [-14.   4.   2.   8.   6.]]
